Repository vinjatovix/ts-api, pull requests merged in 2023-10, with the labels that each got.

#41 Release 1.2.0
  .editorconfig
  .env_example
  .eslintrc.json
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/build_matrix.yml
  .github/workflows/sonar_check.yml
  .gitignore
  .husky/pre-commit
  .husky/pre-push
  .prettierrc
  Dockerfile
  LICENSE.md
  README.md
  cucumber.js
  docker-compose.yaml
  jest.config.js
  package-lock.json
  package.json
  scripts/update_readme_version.sh
  sonar-project.properties
  src/apps/apiApp/backend/ApiApp.ts
  src/apps/apiApp/backend/controllers/health/GetStatusController.ts
  src/apps/apiApp/backend/dependency-injection/application.yaml
  src/apps/apiApp/backend/dependency-injection/application_dev.yaml
  src/apps/apiApp/backend/dependency-injection/application_local.yaml
  src/apps/apiApp/backend/dependency-injection/application_production.yaml
  src/apps/apiApp/backend/dependency-injection/application_test.yaml
  src/apps/apiApp/backend/dependency-injection/apps/application.yaml
  src/apps/apiApp/backend/dependency-injection/index.ts
  src/apps/apiApp/backend/routes/health/health.routes.ts
  src/apps/apiApp/backend/routes/index.ts
  src/apps/apiApp/backend/server.ts
  src/apps/apiApp/backend/start.ts
  src/apps/apiApp/shared/interfaces/Controller.ts
  tests/Contexts/apiApp/backEnd/health/infraestructure/getStatus.test.ts
  tests/Contexts/apiApp/backEnd/health/unit/getStatusController.test.ts
  tests/Contexts/apiApp/backEnd/unit/apiApp.test.ts
  tests/apps/apiApp/backend/features/health/getStatus.feature
  tests/apps/apiApp/backend/features/step_definitions/controller.steps.ts
  tsconfig.json
  tsconfig.prod.json
Labels: Release

#44 fix(chore): update api folders structure
  cucumber.js
  package.json
  src/apps/apiApp/ApiApp.ts
  src/apps/apiApp/controllers/health/GetStatusController.ts
  src/apps/apiApp/dependency-injection/application.yaml
  src/apps/apiApp/dependency-injection/application_dev.yaml
  src/apps/apiApp/dependency-injection/application_local.yaml
  src/apps/apiApp/dependency-injection/application_production.yaml
  src/apps/apiApp/dependency-injection/application_test.yaml
  src/apps/apiApp/dependency-injection/apps/application.yaml
  src/apps/apiApp/dependency-injection/index.ts
  src/apps/apiApp/routes/health/health.routes.ts
  src/apps/apiApp/routes/index.ts
  src/apps/apiApp/server.ts
  src/apps/apiApp/start.ts
  tests/Contexts/apiApp/health/infraestructure/getStatus.test.ts
  tests/Contexts/apiApp/health/unit/getStatusController.test.ts
  tests/Contexts/apiApp/unit/apiApp.test.ts
  tests/apps/apiApp/features/health/getStatus.feature
  tests/apps/apiApp/features/step_definitions/controller.steps.ts
Labels: enhancement

#48 Release v1.2.1
  .github/workflows/create_tag.yml
  README.md
  cucumber.js
  docker-compose.yaml
  package-lock.json
  package.json
  scripts/update_readme_version.sh
  src/apps/apiApp/ApiApp.ts
  src/apps/apiApp/controllers/health/GetStatusController.ts
  src/apps/apiApp/dependency-injection/application.yaml
  src/apps/apiApp/dependency-injection/application_dev.yaml
  src/apps/apiApp/dependency-injection/application_local.yaml
  src/apps/apiApp/dependency-injection/application_production.yaml
  src/apps/apiApp/dependency-injection/application_test.yaml
  src/apps/apiApp/dependency-injection/apps/application.yaml
  src/apps/apiApp/dependency-injection/index.ts
  src/apps/apiApp/routes/health/health.routes.ts
  src/apps/apiApp/routes/index.ts
  src/apps/apiApp/server.ts
  src/apps/apiApp/start.ts
  tests/Contexts/apiApp/health/infraestructure/getStatus.test.ts
  tests/Contexts/apiApp/health/unit/getStatusController.test.ts
  tests/Contexts/apiApp/unit/apiApp.test.ts
  tests/apps/apiApp/features/health/getStatus.feature
  tests/apps/apiApp/features/step_definitions/controller.steps.ts
Labels: release/patch

#90 [GH-89] Prepare release v1.3.0
  README.md
  docker-compose.yaml
  package-lock.json
  package.json
Labels: release/minor
